FROM python:3.9-slim

WORKDIR /server

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Install caffix/amass and theharvester
RUN apt-get update && apt-get install -y \
    docker \
    && rm -rf /var/lib/apt/lists/*
RUN docker pull caffix/amass
RUN docker pull theharvester

COPY . .

EXPOSE 5000

CMD ["python", "server.py"]
